### ISSUE TITLE
Refactor input using configs

### ISSUE THREAD

**Issue by iejMac** [iejMac/video2dataset#202]
Now we have many many parameters to video2dataset and most of them you probably don't want changed and in some of them the structure is hierarchal so an OmegaConf config system seems reasonable. Let's have a look. Current Params:

```
    url_list: str,
    output_folder: str = "videos",
    processes_count: int = 1,
    thread_count: int = 16,
    output_format: str = "files",
    input_format: str = "txt",
    url_col: str = "url",
    caption_col: Optional[str] = None,
    clip_col: Optional[str] = None,
    save_additional_columns: Optional[List[str]] = None,
    number_sample_per_shard: int = 10000,
    enable_wandb: bool = False,
    wandb_project: str = "video2dataset",
    oom_shard_count: int = 5,
    distributor: str = "multiprocessing",
    subjob_size: int = 1000,
    incremental_mode: str = "incremental",
    max_shard_retry: int = 1,
    video_size: int = 360,
    video_fps: int = -1,
    resize_mode: Optional[List[str]] = None,
    audio_rate: int = -1,
    timeout: int = 60,
    tmp_dir: str = "/tmp",
    yt_metadata_args: dict = None,
    captions_are_subtitles: bool = False,
    detect_cuts: bool = False,
    cut_detection_mode: str = "all",
    cut_framerates: list = None,
    cuts_are_clips: bool = False,
    cut_detector_threshold: int = 27,
    cut_detector_min_scene_len: int = 15,
    encode_formats: dict = None,
    stage: str = "download",
    optical_flow_params: dict = None,
    min_clip_length: float = 0.0,
    max_clip_length: float = 999999.0,
    max_clip_length_strategy: str = "all",
    clipping_precision: str = "low",
    extract_compression_metadata: bool = False,
    sampler=None,
    slurm_cpus_per_task: int = 1,
    slurm_job_name: str = "video2dataset",
    slurm_partition: str = None,
    slurm_n_nodes: int = 1,
    slurm_gpus_per_node: int = 8,
    slurm_account: str = None,
    slurm_tasks_per_node: int = 1,
    slurm_nodelist: str = None,
    slurm_exclude: str = None,
    slurm_cache_path: str = None,
    slurm_timeout: int = None,
    slurm_verbose_wait: bool = False,
```

I need to partition out what to make configs for because it's *probably* not everything. So I think you should be able to pass in a config for every single param BUT you should also be able to manually overwrite SOME params (like url_list). Here's an example config:

```yaml
url_list: str,
output_folder: str = "videos",
output_format: str = "files",
input_format: str = "txt",
encode_formats: dict = None,
stage: str = "download",
url_col: str = "url",
caption_col: Optional[str] = None,
clip_col: Optional[str] = None,
save_additional_columns: Optional[List[str]] = None,
enable_wandb: bool = False,
wandb_project: str = "video2dataset",
incremental_mode: str = "incremental",
max_shard_retry: int = 1,
tmp_dir: str = "/tmp",

subsampling:
    ResolutionSubsampler:
        args:
            video_size: int = 360,
            resize_mode: Optional[List[str]] = None,
    FrameRateSubsampler:
        args:
           video_fps: int = -1,
    AudioRateSubsampler:
        args:
            audio_rate: int = -1,
    CutDetectionSubsampler:
        detect_cuts: bool = False,
        cuts_are_clips: bool = False,
        args:
            cut_detection_mode: str = "all",
            cut_framerates: list = None,
            cut_detector_threshold: int = 27,
            cut_detector_min_scene_len: int = 15,
    ClippingSubsampler:
        args:
            min_clip_length: float = 0.0,
            max_clip_length: float = 999999.0,
            max_clip_length_strategy: str = "all",
            clipping_precision: str = "low",
    MetadataSubsampler:
        extract_compression_metadata: bool = False,
    OpticalFlowSubsampler: (this would not be present in the config if stage != optical_flow)
        optical_flow_params: dict = None, (this would be expanded)


reading:
    sampler=None,
    yt_metadata_args: dict = None,
    timeout: int = 60,

storage:
    number_sample_per_shard: int = 10000,
    oom_shard_count: int = 5,
    captions_are_subtitles: bool = False,

distribution:
    processes_count: int = 1,
    thread_count: int = 16,
    subjob_size: int = 1000,
    distributor: "slurm"
    distributor_args:
        slurm_cpus_per_task: int = 1,
        slurm_job_name: str = "video2dataset",
        slurm_partition: str = None,
        ...
        slurm_verbose_wait: bool = False,
```
