### ISSUE TITLE
YouTube metadata is not saved

### ISSUE THREAD

**Issue by libeanim** [iejMac/video2dataset#319]
## Issue

When using video2dataset (1.3.0) to download youtube videos i've set the following entry in the config to retrieve meta data:

```yaml
reading:
    yt_args:
        download_size: 360
        download_audio_rate: 44100
        yt_metadata_args:
            writesubtitles: 'all'
            subtitleslangs: ['en', 'de', 'es', 'fr', 'it', 'nl', 'pl', 'ru']
            writeautomaticsub: True
            get_info: True
    timeout: 60
    sampler: null
```

But in the resulting json files the entry `"yt_meta_dict": {}`, is empty even though `get_info: True` in the config.

## How to reproduce

For example this link: https://www.youtube.com/embed/JFUsP1coIKM
When i download that with yt-dlp:
```bash
yt-dlp -N 2 \
       --write-subs --convert-subs srt \
       --write-info-json --embed-subs --embed-chapters --embed-metadata \
       --no-progress -q \
       --format 'b[height<=360][ext=mp4]' \
       --output './demo.mp4' \
       https://www.youtube.com/embed/JFUsP1coIKM
```
I get youtube meta data like `"categories": ["Entertainment"], "tags": ["Deutsche", "Welle", "Made", "in", "Germany", "Bio", "Lettland", "Getreide"]`

But with video2dataset it looks like this:
```json
    "caption": "\"Volles Korn voran\" 28. November 2008 Beitrag \u00fcber den \u00f6kologischen Teil des Ackerbaus von german",
    "url": "https://www.youtube.com/embed/JFUsP1coIKM",
    "key": "0000000",
    "status": "success",
    "error_message": null,
    "yt_meta_dict": {},
    "video_metadata": {...
```
